In [1]:
import  numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_predict

In [8]:
data = np.loadtxt(open('E:/klinghui/00/blood1.csv'),delimiter = ',')

In [9]:
print(data)

[[2.00e+00 5.00e+01 1.25e+04 9.80e+01 1.00e+00]
 [0.00e+00 1.30e+01 3.25e+03 2.80e+01 1.00e+00]
 [1.00e+00 1.60e+01 4.00e+03 3.50e+01 1.00e+00]
 ...
 [2.30e+01 3.00e+00 7.50e+02 6.20e+01 0.00e+00]
 [3.90e+01 1.00e+00 2.50e+02 3.90e+01 0.00e+00]
 [7.20e+01 1.00e+00 2.50e+02 7.20e+01 0.00e+00]]


In [17]:
X = data[:,0:-1]
y = data[:,-1]
print(X,y)

[[2.00e+00 5.00e+01 1.25e+04 9.80e+01]
 [0.00e+00 1.30e+01 3.25e+03 2.80e+01]
 [1.00e+00 1.60e+01 4.00e+03 3.50e+01]
 ...
 [2.30e+01 3.00e+00 7.50e+02 6.20e+01]
 [3.90e+01 1.00e+00 2.50e+02 3.90e+01]
 [7.20e+01 1.00e+00 2.50e+02 7.20e+01]] [1. 1. 1. 1. 0. 0. 1. 0. 1. 1. 0. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1.
 0. 0. 0. 1. 1. 0. 0. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 0. 1. 0. 1. 1. 0. 0.
 0. 0. 0. 1. 0. 0. 1. 1. 1. 1. 0. 0. 0. 1. 0. 1. 1. 0. 1. 0. 0. 0. 0. 0.
 1. 0. 1. 1. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0.
 0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 1.
 1. 1. 1. 1. 0. 0. 1. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 1. 1. 0. 0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.
 0. 0. 0. 0. 0. 1. 1. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.
 1. 0. 1. 1. 0. 0. 0. 0. 0. 0.

In [18]:
from sklearn import metrics
log = LogisticRegression()
y_pred = cross_val_predict(log,X,y,cv =10)
print (metrics.accuracy_score(y,y_pred))

0.7647058823529411


In [21]:
from sklearn.model_selection import LeaveOneOut
loo = LeaveOneOut()
accuracy = 0
for train,test in loo.split(X):
    log.fit(X[train],y[train])
    y_p = log.predict(X[test])
    if y_p == y[test]:
        accuracy += 1
print(accuracy / np.shape(X)[0])

0.7700534759358288
